# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamOfMan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DreamOfMan
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxAlamofire'
  pod 'SwiftyJSON'
  pod 'RxWebKit'

  target 'DreamOfManTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DreamOfManUITests' do
    # Pods for testing
  end

end
